version: '3'
services:
  golem-build:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/go/src/github.com/ushios/golem
  dep:
    build:
      context: .
      dockerfile: Dockerfile.dep
    volumes:
      - .:/go/src/github.com/ushios/golem
