version: '3'
services:
  golem:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/github.com/ushios/golem
  dep:
    build:
      context: .
      dockerfile: Dockerfile.dep
    volumes:
      - .:/go/src/github.com/ushios/golem
