version: '2'
jobs:
  build:
    working_directory: ~/golem
    machine: true
    steps:
      - checkout
      - run:
          name: check docker version
          command: |
            docker version
            docker-compose version
      - run:
          name: get dependencies
          command: |
            make dep
      - run:
          name: build golem
          command: |
            make build
      - run:
          name: docker build test
            docker build .
      - run:
          name: test
          command: |
            make test
